/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_MONGODB_DATA_API_URL:
      process.env.NEXT_PUBLIC_MONGODB_DATA_API_URL,
    NEXT_PUBLIC_MONGODB_DATA_SOURCE:
      process.env.NEXT_PUBLIC_MONGODB_DATA_SOURCE,
    NEXT_PUBLIC_MONGODB_API_KEY: process.env.NEXT_PUBLIC_MONGODB_API_KEY,

    NEXT_PUBLIC_MONGODB_URI: process.env.NEXT_PUBLIC_MONGODB_URI,
    NEXT_PUBLIC_MONGODB_DB: process.env.NEXT_PUBLIC_MONGODB_DB,

    NEXT_PUBLIC_MONGODB_COLLECTION: process.env.NEXT_PUBLIC_MONGODB_COLLECTION,

    PROD_API_KEY: process.env.PROD_API_KEY,
    PROD_MONGODB_URI: process.env.PROD_MONGODB_URI,
    PROD_MONGODB_DB: process.env.PROD_MONGODB_DB,
    PROD_MONGODB_COLLECTION: process.env.PROD_MONGODB_COLLECTION,
    PROD_MONGODB_DATA_SOURCE: process.env.PROD_MONGODB_DATA_SOURCE,
    PROD_MONGODB_DATA_API_URL: process.env.PROD_MONGODB_DATA_API_URL,
  },
};

export default nextConfig;
