import {
  AlertTriangle,
  Check,
  ChevronLeft,
  ChevronRight,
  ClipboardCopy,
  Download,
  File,
  FileText,
  HelpCircle,
  Image,
  Loader2,
  MoreVertical,
  Save,
  Settings,
  Trash,
  Upload,
  X,
} from 'lucide-react';

export const Icons = {
  alertTriangle: AlertTriangle,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboardCopy: ClipboardCopy,
  download: Download,
  file: File,
  fileText: FileText,
  helpCircle: HelpCircle,
  image: Image,
  loader: Loader2,
  more: MoreVertical,
  save: Save,
  settings: Settings,
  trash: Trash,
  upload: Upload,
  x: X,
};
